# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2b609604cfc4dae154401f4afc183a75cef35d92ab01601c5a79c5eb9185980050bbe100930e488249dd104fd3060a1febe3a085bd78247cc5f1f13c2194ce

test:
  secret_key_base: e66602c97da738745b504db1aab17fceafc256257050e5ea4bf4ed10c2f84cda9e34eb86d3e0b7e73c284cd85e7e00c4093c3574f07d12bd0913492a492eb74c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
